/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_satwrapper_CadicalSolver */

#ifndef _Included_org_satwrapper_CadicalSolver
#define _Included_org_satwrapper_CadicalSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_satwrapper_CadicalSolver
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_satwrapper_CadicalSolver_create
  (JNIEnv *, jobject);

/*
 * Class:     org_satwrapper_CadicalSolver
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_satwrapper_CadicalSolver_delete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_satwrapper_CadicalSolver
 * Method:    cadical_add_val
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_satwrapper_CadicalSolver_cadical_1add_1val
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_satwrapper_CadicalSolver
 * Method:    cadical_solve
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_satwrapper_CadicalSolver_cadical_1solve
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_satwrapper_CadicalSolver
 * Method:    cadical_val
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_satwrapper_CadicalSolver_cadical_1val
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_satwrapper_CadicalSolver
 * Method:    cadical_assume
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_satwrapper_CadicalSolver_cadical_1assume
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_satwrapper_CadicalSolver
 * Method:    cadical_failed
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_satwrapper_CadicalSolver_cadical_1failed
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
